       numpy means numeric python is use for solving numeric problems in python
steps:
       
       

1.   1st import the numpy library
2.  2nd creatina a list in python
3.  3rd converting that list in array using numpy.array or np.array
4.  4th perform operations on that array







In [ ]:
import numpy as np   #importing the numpy

In [ ]:
l=['xyz','a',101,12.05]   #creating a list
l=np.array(l)         #converting that list into a array
l

array(['xyz', 'a', '101', '12.05'], dtype='<U5')

In [ ]:
type(l)       #checking a type of array

numpy.ndarray

In [ ]:
np.array([(1,2),(4,5)])  #creating a 2dimensional array

array([[1, 2],
       [4, 5]])

Parameters of np array
array(object , dtype=None , copy=True , order='k' , subok=False)


1. object  : objects or elements os array
2. dtype   : data-type of elements of array bydefault data-type is None
3. ndmin   : number of dimensions of array (min:2)



**dtype**

*It is also show the data-type of given aaray. also use to convert given elements to define data-type, By default dtype is a None*

In [ ]:
np.array([1,2,3],dtype=complex)     #creating a array of complex numbers

array([1.+0.j, 2.+0.j, 3.+0.j])

*dtype consisting of more than one element*

In [ ]:
x=np.array([(1,2),(3,4)],dtype=[('a',float),('b',complex)])     #it can be convert 'a' means [0]index element=1,3 to float and 'a' means [1]index element=2,4 to complex
x

array([(1., 2.+0.j), (3., 4.+0.j)], dtype=[('a', '<f8'), ('b', '<c16')])

Creating a matrix using numpy


In [ ]:
a=np.mat([(1,2),(4,5)]) 
a

matrix([[1, 2],
        [4, 5]])

In [ ]:
type(a)

numpy.matrix

In [ ]:
np.mat('1,2;3,4')   #creating a matrix using string

matrix([[1, 2],
        [3, 4]])

**creating an array**

There is 3 ways to create an array


1. np.array()
2. np.asarray()
3. np.asanyarray()



In [ ]:
np.array([1,2,3,4,5])    #creatin an array using as array()

array([1, 2, 3, 4, 5])

**np.asarray()**

In [ ]:
a=np.asarray([1,2,3])  #creatin an array using as asarray()
a

array([1, 2, 3])

In [ ]:
np.mat(a)          #converting array into matrix

matrix([[1, 2, 3]])

In [ ]:
np.asarray([1,2,3],dtype=float)        #converting matrix into array

array([1., 2., 3.])

**asanyarray()**

In [ ]:

a=np.asanyarray([1,2,3])    #creatin an array using as asanyarray()
a

array([1, 2, 3])

In [ ]:
a=np.mat(a)         #converting array into matrix
a

matrix([[1, 2, 3]])

In [ ]:
a=np.asanyarray(a)       #converting matrix into array
a

matrix([[1, 2, 3]])

*note:array() & asarray() can be covert pre define matrix into array but asanyarray() can not convert pre define matrix into array because matrux is a subser of array is show in above example *

**issubclass**

In [ ]:
issubclass(np.ndarray,np.matrix)  #False beacuse array is not sub_class of matrix

False

In [ ]:
issubclass(np.matrix,np.ndarray)      #True beacuse matrix is a sub_class of array

True

**copy()**

**copy() is use for create a deep copy of main array into another array**

In [ ]:
x=np.array([1,2,3])
x


array([1, 2, 3])

In [ ]:
z=np.copy(x)
z

array([1, 2, 3])

In [ ]:
z[0]=50
z

array([50,  2,  3])

In [ ]:
x

array([1, 2, 3])

**In above example shows that the cpoy() pointing to the another location. z & x are pointing two different locations.This is called as deep copy**

*fromfunction()*

**This is use for generating a array based on the any condition or function**

In [ ]:
np.fromfunction(lambda i,j:i==j,(3,3),dtype=int)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [ ]:
np.fromfunction(lambda i,j:i*j,(3,3),dtype=int)

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

**fromiter**

 if we want a generate an array by using iterator or genrator then we can use this function

In [ ]:
iterable=(x*x for x in range(5))   #This function is create a list of length(5)

In [ ]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

**fromstring**

if we want a generate an array by using string then we can use this function
This fuction base on 'sep' parameter array will be created or convered

In [ ]:
a=np.fromstring('123 234 345',sep=' ')
a

array([123., 234., 345.])

In [ ]:
np.fromstring('1,2,3,2,3,4,3,4,5',sep=',')

array([1., 2., 3., 2., 3., 4., 3., 4., 5.])

**Create a record array from a list of array**

In [ ]:
x1=np.array([1,2,3,4])
x2=np.array(['aa','bb','cc','dd'])
x3=np.array([1.1,2.2,3.3,4.4])
xx4=np.array([1.1,2,3,4])

In [ ]:
np.core.records.fromarrays([x1,x2,x3,x3])

rec.array([(1, 'aa', 1.1, 1.1), (2, 'bb', 2.2, 2.2), (3, 'cc', 3.3, 3.3),
           (4, 'dd', 4.4, 4.4)],
          dtype=[('f0', '<i8'), ('f1', '<U2'), ('f2', '<f8'), ('f3', '<f8')])

**dtype**

In [ ]:
a=[[1,2,3],[4,5,6],[7,8,9]]
mat=np.array(a)

In [ ]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
print("dimension of this matrix:",mat.ndim,sep='')

dimension of this matrix:2


In [ ]:
print("size of this matrix:",mat.size,sep='')

size of this matrix:9


In [ ]:
print("shape of this matrix:",mat.shape,sep='')

shape of this matrix:(3, 3)


In [ ]:
print("Data type of this matrix:",mat.dtype,sep="")

Data type of this matrix:int64


**arange and linspace**

**arange**
the arange is same as the python range but main diffrerence that the python range() can be acceptr only int valu and numpy.arange() van be accept float value also




In [ ]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [ ]:
np.arange(5,15,2.5)

array([ 5. ,  7.5, 10. , 12.5])

In [ ]:
np.arange(5,15,2)

array([ 5,  7,  9, 11, 13])

In [ ]:
np.arange(5.5,15,2.5)

array([ 5.5,  8. , 10.5, 13. ])

In [ ]:
np.arange(16,0,-2)

array([16, 14, 12, 10,  8,  6,  4,  2])

**linspace**


linspace is use for generating a number of data into satatong point and ending point

In [ ]:
np.linspace(1,5,50) #this example shows that the starting point is 1 and ending point is 5 and makes a 1-5 into 50 parts

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [ ]:
np.linspace(1,5,10,endpoint=False)  #if we dont want end point then we can set as endpoint=False

array([1. , 1.4, 1.8, 2.2, 2.6, 3. , 3.4, 3.8, 4.2, 4.6])

In [ ]:
np.linspace(2,3,5,retstep=True)  #restep means the distance between 2 steps

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)

**zeros**

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

**ones**

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.ones((3,2,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [ ]:
#Matrix of 5

4+np.ones((3,5))

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

**empty**

It can be returns a previeus array if threr is notjing have any array then it can be return empty array

**eye**

It can be return a identity matrix

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

**logspace**

In [ ]:
np.logspace(2.0,3.0,num=4,base=10)

array([ 100.        ,  215.443469  ,  464.15888336, 1000.        ])

In [ ]:
np.logspace(2.0,3.0,num=4,endpoint=False)

array([100.        , 177.827941  , 316.22776602, 562.34132519])

In [ ]:
np.logspace(2.0,3.0,num=4,base=2)

array([4.        , 5.0396842 , 6.34960421, 8.        ])

**reshape**

reshape is use for reshaping an array or change the shape of array.Every time if we want to reshape the data ,dimension and shape should always be equal to the no. of multiples of data which is always is availabe otherwise we can be get error

In [ ]:
x=np.arange(16)
x.reshape((-1,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
np.arange(16).reshape((8,2,1))

array([[[ 0],
        [ 1]],

       [[ 2],
        [ 3]],

       [[ 4],
        [ 5]],

       [[ 6],
        [ 7]],

       [[ 8],
        [ 9]],

       [[10],
        [11]],

       [[12],
        [13]],

       [[14],
        [15]]])

**diag**

If we want to get in  diagonal then we can use this function

In [ ]:
x=np.arange(1,17).reshape((4,-1))
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
np.diag(x)

array([ 1,  6, 11, 16])

In [ ]:
np.diag(x,k=2)

array([3, 8])

In [ ]:
np.diag(x,k=-1)

array([ 5, 10, 15])

In [ ]:
np.diag(np.diag(x))

array([[ 1,  0,  0,  0],
       [ 0,  6,  0,  0],
       [ 0,  0, 11,  0],
       [ 0,  0,  0, 16]])

In [ ]:
np.diag(x,k=4)  #it can be return empty because k=4 is not in array

array([], dtype=int64)

**diagflat**

diagflat is use to convert flattened list into a diagonal array

In [ ]:
np.diagflat([[1,2],[3,4]])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [ ]:
np.diagflat([1,2],1)

array([[0, 1, 0],
       [0, 0, 2],
       [0, 0, 0]])

In [ ]:
np.diagflat([1,2],-1)

array([[0, 0, 0],
       [1, 0, 0],
       [0, 2, 0]])

**tri (trigonal)**

In [ ]:
np.tri(3,3,0, dtype=int)#there is a no. of rows and coloumns is 3 and k=0 means from k=0 to lower part of array is 1

array([[1, 0, 0],
       [1, 1, 0],
       [1, 1, 1]])

In [ ]:
np.tri(3,5,k=-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.]])

In [ ]:
np.tri(3,3,k=1)

array([[1., 1., 0.],
       [1., 1., 1.],
       [1., 1., 1.]])

**tril**

return a lower triangle of an array and rest of array is 0

In [ ]:
np.tril([[1,2,3],[4,5,6],[7,8,9]],0)

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [ ]:
np.tril([[1,2,3],[4,5,6],[7,8,9]],1)

array([[1, 2, 0],
       [4, 5, 6],
       [7, 8, 9]])

**triu**

return a upper triangle of an array and rest of array is 0

In [ ]:
np.triu([[1,2,3],[4,5,6],[7,8,9]],0)

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])

In [ ]:
np.triu([[1,2,3],[4,5,6],[7,8,9]],1)

array([[0, 2, 3],
       [0, 0, 6],
       [0, 0, 0]])

# Random number generation

**random.rand**

can be genarate array of given shape with uniform distribution (means between '0-1)

In [ ]:
np.random.rand(2,3)

array([[0.01123893, 0.51850712, 0.4142182 ],
       [0.85610754, 0.62142111, 0.9085043 ]])

**random.randn**

can be genarate array of given shape with normal distribution with zero mean and standard deviation

In [ ]:
np.random.randn(2,3)

array([[-0.53251373,  1.22692444,  1.54382879],
       [ 0.62942413,  0.45484622, -1.54343442]])

**random.randint**

can be genarate a array or a random number between starting_point and ending_point

In [ ]:
np.random.randint(1,10)

7

In [ ]:
np.random.randint(1,100,(4,4))

array([[82, 29, 43, 52],
       [69,  8, 32, 91],
       [80,  5, 61, 58],
       [35, 68, 51, 56]])

In [ ]:
np.random.randint(1,7,20)  #creating 20 samples with random no. 1 to 6

array([5, 4, 2, 4, 5, 2, 5, 5, 2, 3, 4, 6, 5, 1, 5, 3, 2, 1, 1, 4])

**reshaping**

In [ ]:
a=np.random.randint(1,100,30)
a

array([59, 99, 53, 96, 82, 11, 88, 84, 31, 14, 10, 95, 15, 31, 79, 88, 28,
       90, 22, 82, 60, 17, 57, 77,  9, 41, 79, 59, 72,  8])

In [ ]:
b=a.reshape(2,3,5)
b

array([[[59, 99, 53, 96, 82],
        [11, 88, 84, 31, 14],
        [10, 95, 15, 31, 79]],

       [[88, 28, 90, 22, 82],
        [60, 17, 57, 77,  9],
        [41, 79, 59, 72,  8]]])

In [ ]:
c=a.reshape(6,-1)
c

array([[59, 99, 53, 96, 82],
       [11, 88, 84, 31, 14],
       [10, 95, 15, 31, 79],
       [88, 28, 90, 22, 82],
       [60, 17, 57, 77,  9],
       [41, 79, 59, 72,  8]])

**shape**

It can be return a shape of array

**sort**

In [ ]:
a=np.random.randint(1,100,10)
a

array([94, 40, 73,  6, 84, 21, 42, 88, 77,  1])

In [ ]:
np.sort(a)

array([ 1,  6, 21, 40, 42, 73, 77, 84, 88, 94])

In [ ]:
x=np.random.randint(1,100,60).reshape(4,5,3)
x

array([[[42, 96, 98],
        [ 2, 69,  5],
        [11, 53, 16],
        [85, 58, 90],
        [30, 92, 44]],

       [[24, 97,  3],
        [62, 97, 72],
        [44, 35, 34],
        [91, 57, 23],
        [38, 10, 68]],

       [[79, 96, 91],
        [74, 91, 42],
        [90, 92, 29],
        [15, 54,  7],
        [78, 74, 79]],

       [[12, 51, 25],
        [78, 51,  3],
        [ 5, 63, 36],
        [26, 58, 43],
        [97, 17, 21]]])

In [ ]:
np.sort(x,axis=0)

array([[[12, 51,  3],
        [ 2, 51,  3],
        [ 5, 35, 16],
        [15, 54,  7],
        [30, 10, 21]],

       [[24, 96, 25],
        [62, 69,  5],
        [11, 53, 29],
        [26, 57, 23],
        [38, 17, 44]],

       [[42, 96, 91],
        [74, 91, 42],
        [44, 63, 34],
        [85, 58, 43],
        [78, 74, 68]],

       [[79, 97, 98],
        [78, 97, 72],
        [90, 92, 36],
        [91, 58, 90],
        [97, 92, 79]]])

In [ ]:
x=np.random.randint(1,100,25).reshape(5,5)
x

array([[20, 90, 87,  4, 24],
       [85, 13, 84, 62, 59],
       [ 4, 85, 42, 97, 21],
       [50, 94, 74, 97, 10],
       [ 4, 74, 66, 86, 39]])

In [ ]:
np.sort(x,axis=1)

array([[ 4, 20, 24, 87, 90],
       [13, 59, 62, 84, 85],
       [ 4, 21, 42, 85, 97],
       [10, 50, 74, 94, 97],
       [ 4, 39, 66, 74, 86]])

**max**

In [ ]:
a=np.array([15,33,40,5,20])
a.max()

40

**argmax()**

argmax can be return a index of max value

In [ ]:
a=np.array([15,33,40,5,20])
a.argmax()

2

In [ ]:
a=np.random.randint(1,100,15).reshape(5,3)
a

array([[19, 29, 54],
       [31, 32, 14],
       [79, 64, 44],
       [35, 31, 57],
       [55, 12,  2]])

In [ ]:
a.argmax(axis=1)#here output is 5 becuase there is axis=1 hence no. of rows=5

array([2, 1, 0, 2, 0])

**Indexing & slicing**

In [ ]:
arr=np.random.randint(0,100,10)
arr

array([72, 82, 77, 80, 35, 24,  7, 21,  2, 70])

In [ ]:
arr[3]

80

In [ ]:
arr[:4]

array([72, 82, 77, 80])

In [ ]:
arr[-1:6:-1]

array([70,  2, 21])

In [ ]:
a=np.random.randint(1,100,15).reshape(5,3)
a

array([[87, 86, 96],
       [26,  9, 77],
       [87, 97, 54],
       [63, 59,  4],
       [36, 48, 12]])

In [ ]:
a[1]  #getting a 2nd column

array([26,  9, 77])

In [ ]:
a[1:4]  #getting a 2nd to 4th column

array([[26,  9, 77],
       [87, 97, 54],
       [63, 59,  4]])

In [ ]:
a[:,1]  #getting a 2nd row

array([86,  9, 97, 59, 48])

In [ ]:
a[:,1:3]

array([[86, 96],
       [ 9, 77],
       [97, 54],
       [59,  4],
       [48, 12]])

In [ ]:
a[1,1:3]

array([ 9, 77])

In [ ]:
a[1:4,1:3]

array([[ 9, 77],
       [97, 54],
       [59,  4]])

In [ ]:
a[1:4,1]

array([ 9, 97, 59])

In [ ]:
a=np.random.randint(1,100,32).reshape(2,4,4)
a

array([[[86, 99, 98, 23],
        [46, 13, 13, 55],
        [54, 46, 96, 34],
        [37, 73, 28, 39]],

       [[65, 69, 85, 73],
        [84, 95, 15, 92],
        [54, 91, 97, 71],
        [56, 14, 31, 50]]])

In [ ]:
a[0][2]

array([54, 46, 96, 34])

In [ ]:
a[0][1:3]

array([[46, 13, 13, 55],
       [54, 46, 96, 34]])

In [ ]:
a[1][:,1:3]

array([[69, 85],
       [95, 15],
       [91, 97],
       [14, 31]])

In [ ]:
a[0:2,0:2]

array([[[86, 99, 98, 23],
        [46, 13, 13, 55]],

       [[65, 69, 85, 73],
        [84, 95, 15, 92]]])

In [ ]:
a[0][1:3,1:3]

array([[13, 13],
       [46, 96]])

**subseting**

In [ ]:
a=np.random.randint(10,100,15).reshape(3,5)
a

array([[31, 47, 28, 93, 91],
       [68, 77, 15, 88, 13],
       [52, 44, 96, 79, 40]])

In [ ]:
a>50  #if value in a is greater than 50 then return True else false

array([[False, False, False,  True,  True],
       [ True,  True, False,  True, False],
       [ True, False,  True,  True, False]])

**Universal Function**

In [ ]:
a=np.random.randint(1,10,9).reshape(3,3)
b=np.random.randint(1,10,9).reshape(3,3)

In [ ]:
a

array([[6, 2, 2],
       [9, 8, 7],
       [9, 5, 4]])

In [ ]:
b

array([[6, 4, 6],
       [8, 9, 4],
       [9, 9, 6]])

In [ ]:
a*b

array([[36,  8, 12],
       [72, 72, 28],
       [81, 45, 24]])

In [ ]:
a@b

array([[ 70,  60,  56],
       [181, 171, 128],
       [130, 117,  98]])

In [ ]:
a/b

array([[1.        , 0.5       , 0.33333333],
       [1.125     , 0.88888889, 1.75      ],
       [1.        , 0.55555556, 0.66666667]])

In [ ]:
a+100

array([[106, 102, 102],
       [109, 108, 107],
       [109, 105, 104]])

In [ ]:
a**2

array([[36,  4,  4],
       [81, 64, 49],
       [81, 25, 16]])

In [ ]:
pow(a,2)

array([[36,  4,  4],
       [81, 64, 49],
       [81, 25, 16]])

**Brodcasting**

In [ ]:
a=np.zeros((4,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
a+=100 #this is a element brodcasting because we can add 100 in every or all element
a

array([[100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.]])

In [ ]:
b=np.array([1,0,2,5])
b

array([1, 0, 2, 5])

In [ ]:
y=a+b #this is a row wise brodcasting because we can add row in every row
y

array([[101., 100., 102., 105.],
       [101., 100., 102., 105.],
       [101., 100., 102., 105.],
       [101., 100., 102., 105.]])

In [ ]:
c=np.array([0,1,2,3])
c

array([0, 1, 2, 3])

In [ ]:
x=a+c   #this is a column wise brodcasting because we can add row in every column
x

array([[100., 101., 102., 103.],
       [100., 101., 102., 103.],
       [100., 101., 102., 103.],
       [100., 101., 102., 103.]])

**Transpose option**

In [ ]:
a=np.array([[1,2,3,4]])
a

array([[1, 2, 3, 4]])

In [ ]:
a.T

array([[1],
       [2],
       [3],
       [4]])

**array math**

In [ ]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081, 2.        ]])

In [ ]:
np.exp(a)

array([[ 2.71828183,  7.3890561 , 20.08553692, 54.59815003]])

In [ ]:
np.log10(a)

array([[0.        , 0.30103   , 0.47712125, 0.60205999]])

In [ ]:
np.fmod(a,b)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in fmod
  """Entry point for launching an IPython kernel.


array([[0, 0, 1, 4]])